
CREATE DATABASE QUANLYGIAOVU
USE QUANLYGIAOVU

-- TAO BANG THUOC TINH
CREATE TABLE KHOA (
	MAKHOA VARCHAR(4) PRIMARY KEY,
	TENKHOA VARCHAR(40),
	NGTLAP SMALLDATETIME,
	TRGKHOA CHAR(4),
)
GO

CREATE TABLE MONHOC (
	MAMH VARCHAR(10) PRIMARY KEY,
	TENMH VARCHAR(40),
	TCLT TINYINT,
	TCTH TINYINT,
	MAKHOA VARCHAR(4),
)
GO

CREATE TABLE DIEUKIEN (
	MAMH CHAR(10),
	MAMH_TRUOC VARCHAR(10),
	PRIMARY KEY (MAMH, MAMH_TRUOC),
)
GO

CREATE TABLE GIAOVIEN (
	MAGV CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(40),
	HOCVI VARCHAR(10),
	HOCHAM VARCHAR(10),
	GIOITINH VARCHAR(3),
	NGSINH SMALLDATETIME,
	NGVL SMALLDATETIME,
	HESO NUMERIC(4,2),
	MUCLUONG MONEY,
	MAKHOA VARCHAR(4),
)
GO

CREATE TABLE LOP (
	MALOP CHAR(3) PRIMARY KEY,
	TENLOP VARCHAR(40),
	TRGLOP VARCHAR(5),
	SISO TINYINT,
	MAGVCN CHAR(4),
)
GO

CREATE TABLE HOCVIEN (
	MAHV CHAR(5) PRIMARY KEY,
	HO VARCHAR(40),
	TEN VARCHAR(10),
	NGSINH SMALLDATETIME,
	GIOITINH VARCHAR(3),
	NOISINH VARCHAR(40),
	MALOP CHAR(3),
)
GO

CREATE TABLE GIANGDAY (
	MALOP CHAR(3),
	MAMH VARCHAR(10),
	PRIMARY KEY(MALOP, MAMH),
	MAGV CHAR(4),
	HOCKY TINYINT,
	NAM SMALLINT,
	TUNGAY SMALLDATETIME,
	DENNGAY SMALLDATETIME,
)
GO

CREATE TABLE KETQUATHI (
	MAHV char(5),
	MAMH varchar(10),
	LANTHI TINYINT,
	PRIMARY KEY(MAHV, MAMH, LANTHI),
	NGTHI SMALLDATETIME,
	DIEM NUMERIC(4,2),
	KQUA VARCHAR(10),
)
GO

-- CAU 1
ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KETQUATHI_HOCVIEN FOREIGN KEY (MAHV)
REFERENCES HOCVIEN(MAHV)
GO

ALTER TABLE LOP
ALTER COLUMN TRGLOP CHAR(5)
GO

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_HOCVIEN FOREIGN KEY (TRGLOP)
REFERENCES HOCVIEN(MAHV)
GO

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_GIAOVIEN FOREIGN KEY(MAGVCN)
REFERENCES GIAOVIEN(MAGV)
GO