
CREATE DATABASE QUANLYGIAOVU
USE QUANLYGIAOVU

-- TAO BANG THUOC TINH
CREATE TABLE KHOA (
	MAKHOA VARCHAR(4) PRIMARY KEY,
	TENKHOA VARCHAR(40),
	NGTLAP SMALLDATETIME,
	TRGKHOA CHAR(4),
)
GO

CREATE TABLE MONHOC (
	MAMH VARCHAR(10) PRIMARY KEY,
	TENMH VARCHAR(40),
	TCLT TINYINT,
	TCTH TINYINT,
	MAKHOA VARCHAR(4),
)
GO

CREATE TABLE DIEUKIEN (
	MAMH CHAR(10),
	MAMH_TRUOC VARCHAR(10),
	PRIMARY KEY (MAMH, MAMH_TRUOC),
)
GO

CREATE TABLE GIAOVIEN (
	MAGV CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(40),
	HOCVI VARCHAR(10),
	HOCHAM VARCHAR(10),
	GIOITINH VARCHAR(3),
	NGSINH SMALLDATETIME,
	NGVL SMALLDATETIME,
	HESO NUMERIC(4,2),
	MUCLUONG MONEY,
	MAKHOA VARCHAR(4),
)
GO

CREATE TABLE LOP (
	MALOP CHAR(3) PRIMARY KEY,
	TENLOP VARCHAR(40),
	TRGLOP VARCHAR(5),
	SISO TINYINT,
	MAGVCN CHAR(4),
)
GO

CREATE TABLE HOCVIEN (
	MAHV CHAR(5) PRIMARY KEY,
	HO VARCHAR(40),
	TEN VARCHAR(10),
	NGSINH SMALLDATETIME,
	GIOITINH VARCHAR(3),
	NOISINH VARCHAR(40),
	MALOP CHAR(3),
)
GO

CREATE TABLE GIANGDAY (
	MALOP CHAR(3),
	MAMH VARCHAR(10),
	PRIMARY KEY(MALOP, MAMH),
	MAGV CHAR(4),
	HOCKY TINYINT,
	NAM SMALLINT,
	TUNGAY SMALLDATETIME,
	DENNGAY SMALLDATETIME,
)
GO

CREATE TABLE KETQUATHI (
	MAHV char(5),
	MAMH varchar(10),
	LANTHI TINYINT,
	PRIMARY KEY(MAHV, MAMH, LANTHI),
	NGTHI SMALLDATETIME,
	DIEM NUMERIC(4,2),
	KQUA VARCHAR(10),
)
GO


-- CAU 1
ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KETQUATHI_HOCVIEN FOREIGN KEY (MAHV)
REFERENCES HOCVIEN(MAHV)
GO

ALTER TABLE LOP
ALTER COLUMN TRGLOP CHAR(5)
GO

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_HOCVIEN FOREIGN KEY (TRGLOP)
REFERENCES HOCVIEN(MAHV)
GO

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_GIAOVIEN FOREIGN KEY(MAGVCN)
REFERENCES GIAOVIEN(MAGV)
GO

ALTER TABLE KHOA
ADD CONSTRAINT FK_KHOA_GIAOVIEN FOREIGN KEY(TRGKHOA)
REFERENCES GIAOVIEN(MAGV)
GO

ALTER TABLE MONHOC
ADD CONSTRAINT FK_MONHOC_KHOA FOREIGN KEY(MAKHOA)
REFERENCES KHOA(MAKHOA)
GO

ALTER TABLE DIEUKIEN
ALTER COLUMN MAMH VARCHAR(10)
GO

ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DIEUKIEN_MONHOC FOREIGN KEY(MAMH)
REFERENCES MONHOC(MAMH)
GO

SP_FKEYS 'DIEUKIEN'

DROP TABLE DIEUKIEN

CREATE TABLE DIEUKIEN (
	MAMH VARCHAR(10),
	MAMH_TRUOC VARCHAR(10),
	PRIMARY KEY (MAMH, MAMH_TRUOC),
)
GO

ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DIEUKIEN_MONHOC FOREIGN KEY(MAMH)
REFERENCES MONHOC(MAMH)
GO

ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DIEUKIEN_MONHOC_2 FOREIGN KEY(MAMH_TRUOC)
REFERENCES MONHOC(MAMH)
GO

ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_GIAOVIEN_KHOA FOREIGN KEY(MAKHOA)
REFERENCES KHOA(MAKHOA)
GO

ALTER TABLE HOCVIEN
ADD CONSTRAINT FK_HOCVIEN_LOP FOREIGN KEY(MALOP)
REFERENCES LOP(MALOP)
GO

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GIANGDAY_LOP FOREIGN KEY(MALOP)
REFERENCES LOP(MALOP)
GO

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GIANGDAY_MONHOC FOREIGN KEY(MAMH)
REFERENCES MONHOC(MAMH)
GO

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GIANGDAY_GIAOVIEN FOREIGN KEY(MAGV)
REFERENCES GIAOVIEN(MAGV)
GO

ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KETQUATHI_MONHOC FOREIGN KEY(MAMH)
REFERENCES MONHOC(MAMH)
GO

-- CAU 1 
ALTER TABLE HOCVIEN
ADD GHICHU VARCHAR(100),
	DIEMTB NUMERIC(4, 2),
	XEPLOAI VARCHAR(20)
GO

-- CAU 2
ALTER TABLE HOCVIEN
ADD CONSTRAINT CK_MAHV
CHECK(MAHV LIKE '%%%[0-9][0-9]')
GO

-- CAU 3
ALTER TABLE HOCVIEN
ADD CONSTRAINT CK_GIOITINH
CHECK (GIOITINH IN('Nam', 'Nu'))
GO

-- CAU 4
ALTER TABLE KETQUATHI
ALTER COLUMN DIEM NUMERIC(3,2)

ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_DIEM
CHECK (DIEM BETWEEN 0 AND 10)
GO

-- CAU 5
CREATE TRIGGER TG_UPDATEKQUA
ON KETQUATHI
AFTER UPDATE
AS
BEGIN
	UPDATE KETQUATHI
	SET KQUA = CASE WHEN DIEM >= 5 THEN 'Dat' ELSE 'Khong dat' END
	WHERE MAHV = (SELECT MAHV FROM INSERTED)
END
GO

-- CAU 6
ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_LANTHI
CHECK (LANTHI <= 3)
GO

-- CAU 7
ALTER TABLE GIANGDAY
ADD CONSTRAINT CK_HOCKY
CHECK (HOCKY BETWEEN 1 AND 3)
GO

-- CAU 8
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CK_HOCVI
CHECK (HOCVI IN('CN', 'KS', 'Ths', 'TS', 'PTS'))
GO